[package]
name = "simple_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.16"
malachite-q = "0.2.4"
rand = "0.8.3"
